spring:
  #Application Config
  application:
    name: taco-cloud

  #Cassandra Config
  data:
    cassandra:
      keyspace-name: taco_cloud
      schema-action: recreate
      local-datacenter: datacenter1
      username: tacocloud
      password: admin